### ISSUE TITLE
Could not run µWebSockets bindings on ubuntu 18.04

### ISSUE THREAD

**Issue by micahli** [ClusterWS/ClusterWS#125]
- [ ] Bug
- [X] Question
- [ ] Suggestion
- [ ] Other

Get error when run clusterws@3.2.0 on ubuntu 18.04.
Tried  sudo apt-get install libc6-i386. But it doesn't work.

error info:
/home/ubuntu/MEVServer/NewNodeServer/node_modules/clusterws/index.js:11
        throw new Error("Could not run µWebSockets bindings");
        ^

Error: Could not run µWebSockets bindings
    at /home/ubuntu/MEVServer/NewNodeServer/node_modules/clusterws/index.js:11:15
    at Object.<anonymous> (/home/ubuntu/MEVServer/NewNodeServer/node_modules/clusterws/index.js:13:3)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/ubuntu/MEVServer/NewNodeServer/GameServer.js:6:17)

**Comment by goriunov** [comment]
Check: https://github.com/ClusterWS/ClusterWS/issues/77
